In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3])
print(type(arr), arr)

<class 'numpy.ndarray'> [1 2 3]


In [3]:
arr1 = np.arange(5)
arr2 = np.arange(1,5)
print(arr1)
print(arr2)

[0 1 2 3 4]
[1 2 3 4]


In [4]:
arr = np.arange(10)
print(arr[1::2])

[1 3 5 7 9]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


In [5]:
arr = np.array([1, 2, 3, 4, 5], ndmin=3)

print(arr)
print('No. of dimensions of array:', arr.ndim)
print('Shape of array:', arr.shape)

[[[1 2 3 4 5]]]
No. of dimensions of array: 3
Shape of array: (1, 1, 5)


In [7]:
arr = np.array([1,2,3,4,5,6])
print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]


In [8]:
arr = np.array([1,2,3,4,5,6])
a = arr.reshape(2,3)
b = arr.reshape(3,2)
print('Matrix A:\n', a, '\nMatrix B:\n', b, '\nA*B:\n',np.dot(a,b))

Matrix A:
 [[1 2 3]
 [4 5 6]] 
Matrix B:
 [[1 2]
 [3 4]
 [5 6]] 
A*B:
 [[22 28]
 [49 64]]


In [10]:
from numpy import random
x = random.rand()
print(x)

0.2734180875874165


In [11]:
from numpy import random
x = random.randint(100, size=(3, 3))
print(x)

[[ 5 74 29]
 [92 23 50]
 [70  7 17]]


In [12]:
x.ravel()

array([ 5, 74, 29, 92, 23, 50, 70,  7, 17])